
all:
	gcc -g main.cpp net.cpp audio_openkinect.cpp audioout.cpp -o hollyclient -I/usr/include -I/usr/local/include -I/usr/include/libfreenect -L/usr/local/lib -lfreenect -lstdc++ -lasound -lpthread -Wall




